spring:
  application:
    name: TaoTree
  profiles:
    active:
      - local
  config:
    import:
      - optional:classpath:/config/common/common.yml
      - optional:classpath:/config/common/constants.yml
