spring:
  devtools:
    restart:
      enabled: false
      exclude: static/**,public/**,templates/**

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate: INFO
    p6spy: INFO
  file:
    name: logs/app.log
  logback:
    rollingpolicy:
      file-name-pattern: logs/application-%d{yyyy-MM-dd}-%i.log
      max-file-size: 10MB
      max-history: 30
      total-size-cap: 3GB