spring:
  devtools:
    restart:
      enabled: false
      exclude: static/**,public/**,templates/**

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate: INFO
    p6spy: INFO
  file:
    name: logs/app.log
  logback:
    rollingpolicy:
      file-name-pattern: logs/application-%d{yyyy-MM-dd}-%i.log
      max-file-size: 10MB
      max-history: 30
      total-size-cap: 3GB

# 환경변수 필수 입력 필요
jasypt:
  encryptor:
    password: ${JASYPT_PASSWORD}

decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: true
      logging: slf4j
      # 줄바꿈 \n 사용안됨
      log-file: logs/spy.log
#      log-format: '%(currentTime)|%(executionTime)|%(category)|connection%(connectionId)|%(sql)'
