spring:
  application:
    name: feign-client-app

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8086


feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        decode404: true
