spring:
  jpa:
    hibernate:
      # 테이블 기본 생성 설정
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
  #        format_sql: true

  # database 설정 연결
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: ENC(WxSqvGICAmd2MaKohETMmw==)
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
